openapi: 3.0.3
info:
  title: Shipping Service
  description: Shipping Service
  version: 1.0.0
servers:
  - url: 'http://localhost:8081'
    description: Shipping API server
paths:
  /v1/api/shipping:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderDTO'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: integer
                format: int64
components:
  schemas:
    ShippingDTO:
      type: object
      required:
        - id
        - name
        - address
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        address:
          type: string
    OrderDTO:
      type: object
      required:
        - id
        - orderDate
        - items
        - status
        - name
        - address
      properties:
        id:
          type: integer
          format: int64
        orderDate:
          type: string
          format: date-time
        items:
          type: array
          items:
            type: string
        status:
          type: string
        name:
          type: string
        address:
          type: string
